_target_: evals.datasets.unreal_position.UnrealRelativePosition
root: /path/to/dataset/position_between_objects/forest
split: train
image_size: 224
image_mean: imagenet
reference_label: Rock # Rock, Rock, Tree, Cone
target_label: Tree # Tree, Truck, Truck, Vespa
perspective: human
human_label: Human
exclude_ambiguous: true
ambiguity_degrees: 15 # camera 15, human 10
front_degrees: 45
back_degrees: 135
split_ratio: 0.2 # camera 0.2, human 0.2
test_ratio: 0.1 # camera 0.1, human 0.1
name: unreal_position
