system:
  random_seed: 8
  num_gpus: 1
  port: 12355
note: ""
batch_size: 16
wandb:
  use: True
defaults:
  - optimizer: ten_epoch
  - backbone: dinov2_b14
  - dataset: voc12
  - probe: binaryhead
  - _self_
experiment_name: SSL_Objectness_Probing
experiment_model: dinov2_b14
is_eval: False
ckpt_path: ""
output_dir: "result/objectness_train"
num_workers: 8
model_name: "dinov2_b14"
backbone:
  return_cls: False
  mean_pool: False
  efficient_probe: False
  return_multilayer: True