system:
  random_seed: 8
  num_gpus: 1
  port: 12355
note: ""
batch_size: 4
wandb:
  use: True
defaults:
  - optimizer: ten_epoch
  - backbone: dinov2_b14
  - dataset: nyu
  - probe: snorm_dpt
  - _self_
experiment_name: SSL_SNorm_Probing
experiment_model: dinov2_b14
is_eval: False
ckpt_path: ""
output_dir: "result/snorm_${dataset.name}"
backbone_name: ""
backbone:
  return_multilayer: True