random_seed: 8
split: test
image_size: 800
eval_class: all
num_instances: 200 
image_mean: imagenet
use_bbox: False
multilayer: False
note: ""
defaults:
  - backbone: dinov2_b14
  - _self_
model_name: dinov2_b14
output_dir: result/spair_correspondence
data_root: /shared/sets/datasets/vision/probing_3D/SPair-71k